# generated by fastapi-codegen:
#   filename:  fastapiTest.yaml
#   timestamp: 2022-03-04T22:10:31+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class Nowcast(BaseModel):
    eventId: str
    imageURL: str
    tag: Optional[str] = None


class Nowcasts(BaseModel):
    __root__: List[Nowcast] = Field(..., description='list of Nowcast Images')


class Error(BaseModel):
    code: int
    message: str
