# generated by fastapi-codegen:
#   filename:  fastapi-config.json
#   timestamp: 2022-03-11T03:23:59+00:00

from __future__ import annotations

from typing import Union

from fastapi import FastAPI, Query

from .models import Error, Nowcast, Weatherviz

app = FastAPI(
    version='1.0.0',
    title='SEVIR Data Nowcasting',
    license={'name': 'MIT'},
    servers=[{'url': 'http://sevir-nowcasting.streamlit.io/v1'}],
)


@app.get(
    '/nowcast/{img__id}',
    response_model=Nowcast,
    responses={'default': {'model': Error}},
)
def predict__img(img__id: int = Query(..., alias='img_Id')) -> Union[Nowcast, Error]:
    """
    WWF Weather Nowcasting - Pass Image Id to show 1 out of 12 images
    """
    pass


@app.get(
    '/weatherviz/{state}',
    response_model=Weatherviz,
    responses={'default': {'model': Error}},
)
def filter__nowcast(state: str) -> Union[Weatherviz, Error]:
    """
    WWF Weather visualizations - Get weather visualization stats based on state selection
    """
    pass
