# generated by fastapi-codegen:
#   filename:  fastapi-config.json
#   timestamp: 2022-03-11T03:23:59+00:00

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel


class Nowcast(BaseModel):
    img_Id: int
    tag: Optional[str] = None


class Weatherviz(BaseModel):
    state: str
    tag: Optional[str] = None


class Error(BaseModel):
    code: int
    message: str
